name: Push to GCR
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push-to-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: asia.gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: uploader
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME }},latest
          dockerfile: ./Dockerfile
